from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
from sentence_transformers import SentenceTransformer



DEFAULT_MODEL = "BAAI/bge-m3"
DEFAULT_INPUT = "chunks.json"
DEFAULT_OUTPUT = "embedded_chunks.json"




class LegalEmbedder:


    def __init__(
        self,
        model_name: str = DEFAULT_MODEL,
        device: str | None = None,
        batch_size: int = 16,
    ):
        self.model_name = model_name
        self.batch_size = batch_size

        print(f"Loading embedding model: {model_name}")

        self.model = SentenceTransformer(
            model_name,
            device=device,
        )


        try:
            dimension = self.model.get_embedding_dimension()
        except AttributeError:
            dimension = self.model.get_sentence_embedding_dimension()

        print(f"Embedding dimension: {dimension}")



    def embed_chunks(
        self,
        chunks: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        """
        Create one embedding for every chunk.

        The original chunk dictionary is preserved.
        Only the 'embedding' field is added.

        Chunks with empty / whitespace-only text are skipped (they would
        embed to a meaningless zero vector, and Milvus rejects empty vectors).
        """

        if not chunks:
            return []


        texts = []
        valid_indices = []  

        for i, chunk in enumerate(chunks):

            text = chunk.get("text", "")

            if not isinstance(text, str):
                text = str(text)

            if not text.strip():
                print(
                    f"  [skip] chunk {i} "
                    f"({chunk.get('chunk_id', '?')}) has empty text"
                )
                continue

            texts.append(text)
            valid_indices.append(i)

        if not texts:
            print("No chunks with non-empty text to embed.")
            return []

        print(f"Creating embeddings for {len(texts)} chunks...")

 
        embeddings = self.model.encode(
            texts,
            batch_size=self.batch_size,
            normalize_embeddings=True,
            show_progress_bar=True,
            convert_to_numpy=True,
        )

        embedded_chunks = []

        for idx, embedding in zip(valid_indices, embeddings):

            chunk = chunks[idx]

          
            embedded_chunk = dict(chunk)

            embedded_chunk["embedding"] = (
                embedding.astype(np.float32).tolist()
            )

            embedded_chunks.append(embedded_chunk)

        if len(valid_indices) < len(chunks):
            print(
                f"Skipped {len(chunks) - len(valid_indices)} chunk(s) "
                "with empty text."
            )

        return embedded_chunks




def load_chunks(
    input_path: str | Path,
) -> list[dict[str, Any]]:
    """
    Load chunks.json generated by chunking.py.
    """

    input_path = Path(input_path)

    if not input_path.exists():
        raise FileNotFoundError(
            f"Chunk file not found: {input_path}"
        )

    with input_path.open(
        "r",
        encoding="utf-8",
    ) as file:

        chunks = json.load(file)

    if not isinstance(chunks, list):
        raise ValueError(
            "Expected chunks.json to contain a list of chunks."
        )

    return chunks



def save_embedded_chunks(
    chunks: list[dict[str, Any]],
    output_path: str | Path,
) -> None:
    """
    Save original chunks + embeddings.
    """

    output_path = Path(output_path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with output_path.open(
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            chunks,
            file,
            ensure_ascii=False,
            indent=2,
        )

    print(f"\nSaved embedded chunks to:")
    print(output_path)




def main() -> None:

    parser = argparse.ArgumentParser(
        description=(
            "Generate embeddings for legal chunks "
            "created by chunking.py"
        )
    )

    parser.add_argument(
        "--input",
        default=DEFAULT_INPUT,
        help="Input chunks JSON file",
    )

    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help="Output embedded chunks JSON file",
    )

    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help="Embedding model",
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=16,
        help="Number of chunks embedded at once",
    )

    parser.add_argument(
        "--device",
        default=None,
        help="Embedding device: cpu or cuda",
    )

    args = parser.parse_args()

  

    chunks = load_chunks(args.input)

    print(f"Loaded {len(chunks)} chunks.")



    embedder = LegalEmbedder(
        model_name=args.model,
        device=args.device,
        batch_size=args.batch_size,
    )



    embedded_chunks = embedder.embed_chunks(chunks)

 

    save_embedded_chunks(
        embedded_chunks,
        args.output,
    )

    if embedded_chunks:

        embedding_dimension = len(
            embedded_chunks[0]["embedding"]
        )

        print("\n========================================")
        print("Embedding completed successfully")
        print("========================================")
        print(f"Chunks              : {len(embedded_chunks)}")
        print(f"Embedding model     : {args.model}")
        print(f"Embedding dimension : {embedding_dimension}")
        print(f"Output              : {args.output}")
        print("========================================")


if __name__ == "__main__":
    main()